Mark the current playlist entry

diff --git a/mpvpl b/mpvpl
--- a/mpvpl
+++ b/mpvpl
@@ -21,6 +21,10 @@ channels_in_playlist() {
     jq '[.data[] | .title | values]' <<< "$playlist"
 }
 
+current_entry() {
+    jq -r 'first(.data | to_entries[] | select(.value.current)).key // 0' <<< "$playlist"
+}
+
 tvprog() {
     # shellcheck disable=SC2016
     local epg_query='
@@ -49,13 +53,27 @@ join_tvprog_and_playlist() {
 }
 
 playlist_table() {
-    if [[ -z $epg ]]; then
-        echo $'Title\tPath'
-        playlist_entries
-    else
-        echo $'Channel\tCurrent program\tNext program\tStart'
-        join_tvprog_and_playlist
-    fi | column -t -s $'\t'
+    local temp
+    temp=$(mktemp -p "$tmp_dir")
+
+    if [[ $reload ]]; then
+        if [[ -z $epg ]]; then
+            echo $'Title\tPath'
+            playlist_entries
+        else
+            echo $'Channel\tCurrent program\tNext program\tStart'
+            join_tvprog_and_playlist
+        fi > "$temp"
+
+        # This needs to be atomic because fzf can spawn multiple concurrent processes.
+        mv "$temp" "$PLAYLIST_LAST_RELOAD"
+    fi
+
+    local curr
+    curr=$(current_entry)
+
+    awk -F '\t' 'BEGIN {OFS="\t"} {print (NR == '"$((curr + 2))"') ? "==>" : "", $0}' < "$PLAYLIST_LAST_RELOAD" \
+        | column -t -s $'\t'
 }
 
 fetch_url() {
@@ -146,20 +164,29 @@ Usage: ${0##*/} [ EPG_URL | EPG_PATH ]
 END
 }
 
-cache_dir=${XDG_CACHE_HOME:-~/.cache}/mpv-fzf-playlist
-mpvsocket=${IPC_SOCKET:-/tmp/mpvsocket}
-
-nodownload=""
-reload=""
-epg=""
-
 if [[ $# -eq 1 && ($1 == "--help" || $1 == "-h") ]]; then
     print_usage
     exit
 fi
 
+cache_dir=${XDG_CACHE_HOME:-~/.cache}/mpv-fzf-playlist
+mpvsocket=${IPC_SOCKET:-/tmp/mpvsocket}
+
+nodownload=""
+reload=""
+updatecurr=""
+epg=""
+
+tmp_dir=$(mktemp -d)
+trap 'rm -rf "$tmp_dir"' EXIT
+
 if [[ $# -ge 1 && ($1 == "--nodownload" || $1 == "-D") ]]; then
     nodownload=yes
+    shift
+fi
+
+if [[ $# -eq 1 && $1 == "updatecurr" ]]; then
+    updatecurr=yes
     shift
 fi
 
@@ -187,24 +214,24 @@ if [[ -n $epg ]]; then
 fi
 
 playlist=$(socat - "$mpvsocket" <<< '{"command": ["get_property", "playlist"]}')
+
+# Output erros below to stdout, instead of stderr.
+# Otherwise they will not be shown in fzf.
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
-    echo "Can't connect to mpv. You ran mpv with the --input-ipc-server option set, right?" >&2
+    echo "Can't connect to mpv. You ran mpv with the --input-ipc-server option set, right?"
     exit 1
 fi
 err=$(jq -r .error <<< "$playlist")
 if [[ $err != "success" ]]; then
-    [[ "$err" ]] && echo "mpv error: $err" >&2
+    [[ "$err" ]] && echo "mpv error: $err"
     exit 1
 fi
 
-if [[ $reload ]]; then
+if [[ $reload || $updatecurr ]]; then
     playlist_table
     exit
 fi
-
-tmp_dir=$(mktemp -d)
-trap 'rm -rf "$tmp_dir"' EXIT
 
 if [[ $epg =~ ^https?:// ]]; then
     handle_url "$epg"
@@ -222,6 +249,11 @@ elif [[ $epg =~ \.xml(\.gz)?$ ]]; then
     epg=$converted
 fi
 
-fzf --layout=reverse-list --header-lines=1 --cycle \
+export PLAYLIST_LAST_RELOAD
+PLAYLIST_LAST_RELOAD=$(mktemp -p "$tmp_dir")
+
+# shellcheck disable=SC2016
+fzf --layout=reverse-list --header-lines=1 --cycle --no-sort \
     --bind "start,ctrl-r:reload:${0@Q} reload ${epg@Q}"  \
-    --bind 'enter:execute-silent:socat - '"$mpvsocket"' <<< "{ \"command\": [\"playlist-play-index\", "$(({n} - 1))"] }" > /dev/null'
+    --bind 'enter:execute-silent:socat - '"$mpvsocket"' <<< "{ \"command\": [\"playlist-play-index\", "$(({n} - 1))"] }" > /dev/null' \
+    --bind "enter:+reload:${0@Q} updatecurr"
